using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace TourismApp.Services
{
    public class LanguageService : INotifyPropertyChanged
    {
        public static LanguageService Instance { get; private set; } = default!;

        private string _currentLanguage = "vi";

        public Dictionary<string, string> AvailableLanguages { get; } = new()
        {
            { "🇻🇳 Tiếng Việt", "vi" },
            { "🇺🇸 English", "en" },
            { "🇯🇵 日本語", "ja" },
            { "🇫🇷 Français", "fr" },
            { "🇰🇷 한국어", "ko" },
            { "🇨🇳 中文", "zh" },
            { "🇹🇭 ภาษาไทย", "th" }
        };

        public string CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                if (_currentLanguage != value)
                {
                    _currentLanguage = value.ToLower();
                    OnPropertyChanged(string.Empty);
                    OnPropertyChanged(nameof(CurrentLanguage));
                }
            }
        }

        public LanguageService()
        {
            Instance = this;
            try
            {
                var saved = Microsoft.Maui.Storage.Preferences.Default.Get("UserLanguage", string.Empty);
                if (!string.IsNullOrEmpty(saved))
                    _currentLanguage = saved.ToLower();
            }
            catch { }
        }

        public string this[string key] => GetText(key);

        public string GetText(string key)
        {
            if (Translations.TryGetValue(CurrentLanguage, out var lang) && lang.TryGetValue(key, out var val))
                return val;
            if (Translations["en"].TryGetValue(key, out var fallback))
                return fallback;
            return key;
        }

        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
        {
            // ===================== VIETNAMESE =====================
            ["vi"] = new()
            {
                // Bottom bar
                {"TabHome", "Trang chủ"},
                {"TabExplore", "Khám phá"},
                {"TabScanQR", "Quét QR"},
                {"TabTour", "Tour"},
                {"TabSettings", "Cài đặt"},
                // Home
                {"HomeTitle", "Khu phố ẩm thực Vĩnh Khánh"},
                {"SubTitle", "Thiên đường ốc và hải sản nổi tiếng Quận 4, sôi động về đêm."},
                {"Listen", "Nghe thuyết minh"},
                {"Stop", "Dừng"},
                {"Map", "Xem bản đồ"},
                {"SelectLang", "Chọn ngôn ngữ"},
                {"Cancel", "Hủy"},
                {"NoNarration", "Nhà hàng này hiện chưa có bài thuyết minh nào."},
                {"NoNarrationLang", "Chưa có bản thuyết minh phù hợp với ngôn ngữ đã chọn."},
                // Restaurant detail
                {"RestaurantDetail", "Chi tiết nhà hàng"},
                {"PlayNarration", "▶ Phát thuyết minh"},
                {"StopNarration", "⏹ Dừng thuyết minh"},
                {"MapDirection", "Bản đồ chỉ đường"},
                {"OpenGoogleMaps", "🧭 Mở Google Maps chỉ đường"},
                {"DishList", "Danh sách món ăn"},
                {"PriceFormat", "Giá: {0} đ"},
                {"NoLocation", "📍 Nhà hàng chưa cập nhật tọa độ trên bản đồ. Chủ nhà hàng cần cập nhật vị trí GPS."},
                {"YouAreHere", "Bạn đang ở đây"},
                {"DistanceFormat", "📍 {0} km từ vị trí của bạn"},
                {"NoCoordinate", "📍 Nhà hàng chưa cập nhật tọa độ"},
                {"LoadingAudio", "⏳ Đang tải..."},
                {"DownloadingAudio", "Đang tải audio..."},
                {"PlayingAudio", "Đang phát thuyết minh..."},
                {"PlayingOffline", "Đang phát thuyết minh (offline)..."},
                {"ReadingAloud", "Đang đọc..."},
                {"AudioError", "Lỗi phát audio"},
                // Tour list
                {"TourList", "Tour du lịch"},
                {"ChooseJourney", "Chọn hành trình khám phá ẩm thực"},
                {"NoTours", "Chưa có tour nào"},
                {"Destinations", "điểm đến"},
                {"Free", "Miễn phí"},
                // Tour detail
                {"TourJourney", "Hành trình Tour"},
                {"Previous", "⬅ Trước"},
                {"Next", "Tiếp ➡"},
                {"PlayAudio", "🔊 Nghe"},
                {"StopAudio", "⏹ Dừng"},
                {"Navigate", "🧭 Dẫn đường"},
                {"PointOf", "▶ Điểm {0}/{1}"},
                {"TotalPoints", "Tổng: {0} điểm"},
                {"PointLabel", "ĐIỂM {0}"},
                {"BuyTour", "💳 Mua Tour"},
                {"BuyTourPrice", "💳 Mua {0}đ"},
                {"NeedPayment", "🔒 Cần thanh toán để nghe thuyết minh"},
                {"NeedPaymentPrice", "🔒 Thanh toán {0}đ để nghe thuyết minh"},
                {"NeedPaymentMsg", "Tour này có giá {0}đ. Bạn cần thanh toán để nghe thuyết minh."},
                {"NoNarrationPOI", "Chưa có thuyết minh cho {0}"},
                {"TourNotFound", "Không tìm thấy tour hoặc tour chưa có điểm đến"},
                {"TourLoadError", "Không thể tải tour: {0}"},
                {"PriceTag", "💰 {0}đ"},
                {"FreeTag", "✅ Miễn phí"},
                // Settings
                {"Settings", "⚙️ Cài đặt"},
                {"SettingsTitle", "Cài đặt"},
                {"Profile", "Hồ sơ cá nhân"},
                {"ViewEditProfile", "Xem và chỉnh sửa thông tin cá nhân"},
                {"AnonymousMode", "🕶️ Chế độ ẩn danh"},
                {"AnonymousModeLabel", "Chế độ ẩn danh"},
                {"AnonymousDesc", "Khi bật, dữ liệu di chuyển không gắn với danh tính cá nhân của bạn."},
                {"AnonymousOn", "🟢 ON — Bạn đang ẩn danh ({0})"},
                {"AnonymousOff", "🔴 OFF — Dữ liệu gắn với tài khoản của bạn"},
                {"GpsSettings", "📡 Cài đặt GPS"},
                {"DetectionRadius", "📡 Bán kính phát hiện"},
                {"DetectionRadiusDesc", "Khoảng cách tối đa để tự động phát thuyết minh khi đến gần địa điểm."},
                {"MovementDistance", "🚶 Khoảng cách di chuyển"},
                {"MovementDistanceDesc", "Bạn cần đi ít nhất bao xa để kích hoạt thuyết minh tiếp theo."},
                {"ResetDefault", "🔄 Đặt lại mặc định"},
                {"ServerConnection", "🌐 Kết nối máy chủ"},
                {"ServerIP", "Địa chỉ IP máy chủ"},
                {"ServerIPDesc", "Dùng cho thiết bị thật kết nối qua WiFi."},
                {"OfflineData", "📥 Dữ liệu Offline"},
                {"DownloadOfflineDesc", "Tải dữ liệu để sử dụng khi không có mạng"},
                {"SyncOffline", "📥 Đồng bộ dữ liệu offline"},
                {"SyncingRestaurants", "⏳ Đang đồng bộ nhà hàng..."},
                {"SyncingTours", "⏳ Đang đồng bộ tour..."},
                {"DownloadingAudioFiles", "⏳ Đang tải file audio..."},
                {"SyncSuccess", "✅ Đồng bộ thành công!"},
                {"SyncError", "❌ Lỗi: {0}"},
                {"NeedNetwork", "Cần kết nối mạng để đồng bộ dữ liệu offline."},
                {"NeverSynced", "Chưa đồng bộ"},
                {"LastSyncPrefix", "Lần cuối: {0}"},
                // Profile
                {"ProfileTitle", "Hồ sơ cá nhân"},
                {"Email", "Email"},
                {"Phone", "Số điện thoại"},
                {"Address", "Địa chỉ"},
                {"EditProfile", "✏️ Chỉnh sửa hồ sơ"},
                {"Logout", "🚪 Đăng xuất"},
                {"LogoutConfirm", "Xác nhận"},
                {"LogoutConfirmMsg", "Bạn có chắc chắn muốn đăng xuất?"},
                {"LogoutBtn", "Đăng xuất"},
                {"NotUpdated", "Chưa cập nhật"},
                // Login
                {"Welcome", "Chào mừng quay lại với phố ẩm thực!"},
                {"EmailPlaceholder", "Email của bạn"},
                {"PasswordPlaceholder", "Mật khẩu"},
                {"LoginBtn", "Đăng nhập ngay"},
                {"NoAccount", "Chưa có tài khoản?"},
                {"RegisterNow", "Đăng ký ngay"},
                {"ServerSettings", "⚙ Cài đặt IP máy chủ"},
                {"Authenticating", "Đang xác thực..."},
                {"LoginError", "Tài khoản hoặc mật khẩu không đúng"},
                {"LoginInputError", "Vui lòng nhập đầy đủ email và mật khẩu"},
                {"ConnectionError", "Không thể kết nối đến máy chủ"},
                {"ServerSettingsTitle", "Cài đặt máy chủ"},
                {"ServerSettingsMsg", "Nhập địa chỉ IP WiFi của máy tính\n(chạy 'ipconfig' trên máy tính để xem):"},
                {"ServerSaved", "Đã lưu"},
                {"ServerSavedMsg", "IP máy chủ: {0}\nVui lòng tắt và mở lại app để áp dụng."},
                // Register
                {"RegisterTitle", "ĐĂNG KÝ"},
                {"FullNamePlaceholder", "Họ và tên"},
                {"ChooseAccountType", "Chọn loại tài khoản"},
                {"RegisterBtn", "Đăng ký"},
                {"BackToLogin", "Quay lại đăng nhập"},
                {"RegisterInputError", "Vui lòng nhập đầy đủ thông tin"},
                {"RegisterFailed", "Đăng ký thất bại"},
                {"RegisterSuccess", "Đăng ký thành công"},
                {"Success", "Thành công"},
                {"NoServerConnection", "Không kết nối được tới server"},
                // Common
                {"Error", "Lỗi"},
                {"OK", "OK"},
                {"Confirm", "Xác nhận"},
                {"Close", "Đóng"},
                {"TryAgain", "Thử lại"},
                {"Notification", "Thông báo"},
                {"ErrorLoadInfo", "Không thể tải thông tin"},
                {"ErrorPlay", "Lỗi phát"},
            },

            // ===================== ENGLISH =====================
            ["en"] = new()
            {
                {"TabHome", "Home"},
                {"TabExplore", "Explore"},
                {"TabScanQR", "Scan QR"},
                {"TabTour", "Tour"},
                {"TabSettings", "Settings"},
                {"HomeTitle", "Vinh Khanh Food Street"},
                {"SubTitle", "Famous snail and seafood paradise in District 4, lively at night."},
                {"Listen", "Play Audio"},
                {"Stop", "Stop"},
                {"Map", "View Map"},
                {"SelectLang", "Select Language"},
                {"Cancel", "Cancel"},
                {"NoNarration", "This restaurant currently has no narration."},
                {"NoNarrationLang", "No narration available in the selected language."},
                {"RestaurantDetail", "Restaurant Details"},
                {"PlayNarration", "▶ Play Narration"},
                {"StopNarration", "⏹ Stop Narration"},
                {"MapDirection", "Directions Map"},
                {"OpenGoogleMaps", "🧭 Open Google Maps"},
                {"DishList", "Dish Menu"},
                {"PriceFormat", "Price: {0} VND"},
                {"NoLocation", "📍 Restaurant has not updated its location on the map."},
                {"YouAreHere", "You are here"},
                {"DistanceFormat", "📍 {0} km from your location"},
                {"NoCoordinate", "📍 Restaurant has not updated coordinates"},
                {"LoadingAudio", "⏳ Loading..."},
                {"DownloadingAudio", "Downloading audio..."},
                {"PlayingAudio", "Playing narration..."},
                {"PlayingOffline", "Playing narration (offline)..."},
                {"ReadingAloud", "Reading..."},
                {"AudioError", "Audio playback error"},
                {"TourList", "Travel Tours"},
                {"ChooseJourney", "Choose a food exploration journey"},
                {"NoTours", "No tours available"},
                {"Destinations", "destinations"},
                {"Free", "Free"},
                {"TourJourney", "Tour Journey"},
                {"Previous", "⬅ Previous"},
                {"Next", "Next ➡"},
                {"PlayAudio", "🔊 Listen"},
                {"StopAudio", "⏹ Stop"},
                {"Navigate", "🧭 Navigate"},
                {"PointOf", "▶ Point {0}/{1}"},
                {"TotalPoints", "Total: {0} points"},
                {"PointLabel", "POINT {0}"},
                {"BuyTour", "💳 Buy Tour"},
                {"BuyTourPrice", "💳 Buy {0}₫"},
                {"NeedPayment", "🔒 Payment required to listen to narration"},
                {"NeedPaymentPrice", "🔒 Pay {0}₫ to listen to narration"},
                {"NeedPaymentMsg", "This tour costs {0}₫. You need to pay to listen to narration."},
                {"NoNarrationPOI", "No narration available for {0}"},
                {"TourNotFound", "Tour not found or has no destinations"},
                {"TourLoadError", "Cannot load tour: {0}"},
                {"PriceTag", "💰 {0}₫"},
                {"FreeTag", "✅ Free"},
                {"Settings", "⚙️ Settings"},
                {"SettingsTitle", "Settings"},
                {"Profile", "My Profile"},
                {"ViewEditProfile", "View and edit personal information"},
                {"AnonymousMode", "🕶️ Anonymous Mode"},
                {"AnonymousModeLabel", "Anonymous Mode"},
                {"AnonymousDesc", "When enabled, your movement data is not linked to your identity."},
                {"AnonymousOn", "🟢 ON — You are anonymous ({0})"},
                {"AnonymousOff", "🔴 OFF — Data is linked to your account"},
                {"GpsSettings", "📡 GPS Settings"},
                {"DetectionRadius", "📡 Detection Radius"},
                {"DetectionRadiusDesc", "Maximum distance to auto-play narration when near a location."},
                {"MovementDistance", "🚶 Movement Distance"},
                {"MovementDistanceDesc", "Minimum distance to walk before triggering next narration."},
                {"ResetDefault", "🔄 Reset to Default"},
                {"ServerConnection", "🌐 Server Connection"},
                {"ServerIP", "Server IP Address"},
                {"ServerIPDesc", "For real devices connecting via WiFi."},
                {"OfflineData", "📥 Offline Data"},
                {"DownloadOfflineDesc", "Download data for offline use"},
                {"SyncOffline", "📥 Sync Offline Data"},
                {"SyncingRestaurants", "⏳ Syncing restaurants..."},
                {"SyncingTours", "⏳ Syncing tours..."},
                {"DownloadingAudioFiles", "⏳ Downloading audio files..."},
                {"SyncSuccess", "✅ Sync successful!"},
                {"SyncError", "❌ Error: {0}"},
                {"NeedNetwork", "Network connection required for offline sync."},
                {"NeverSynced", "Never synced"},
                {"LastSyncPrefix", "Last sync: {0}"},
                {"ProfileTitle", "My Profile"},
                {"Email", "Email"},
                {"Phone", "Phone"},
                {"Address", "Address"},
                {"EditProfile", "✏️ Edit Profile"},
                {"Logout", "🚪 Log Out"},
                {"LogoutConfirm", "Confirm"},
                {"LogoutConfirmMsg", "Are you sure you want to log out?"},
                {"LogoutBtn", "Log Out"},
                {"NotUpdated", "Not updated"},
                {"Welcome", "Welcome back to Food Street!"},
                {"EmailPlaceholder", "Your email"},
                {"PasswordPlaceholder", "Password"},
                {"LoginBtn", "Log In"},
                {"NoAccount", "Don't have an account?"},
                {"RegisterNow", "Register Now"},
                {"ServerSettings", "⚙ Server IP Settings"},
                {"Authenticating", "Authenticating..."},
                {"LoginError", "Invalid email or password"},
                {"LoginInputError", "Please enter email and password"},
                {"ConnectionError", "Cannot connect to server"},
                {"ServerSettingsTitle", "Server Settings"},
                {"ServerSettingsMsg", "Enter the WiFi IP address of your computer\n(run 'ipconfig' on your computer to view):"},
                {"ServerSaved", "Saved"},
                {"ServerSavedMsg", "Server IP: {0}\nPlease restart the app to apply."},
                {"RegisterTitle", "REGISTER"},
                {"FullNamePlaceholder", "Full Name"},
                {"ChooseAccountType", "Choose account type"},
                {"RegisterBtn", "Register"},
                {"BackToLogin", "Back to Login"},
                {"RegisterInputError", "Please fill in all fields"},
                {"RegisterFailed", "Registration failed"},
                {"RegisterSuccess", "Registration successful"},
                {"Success", "Success"},
                {"NoServerConnection", "Cannot connect to server"},
                {"Error", "Error"},
                {"OK", "OK"},
                {"Confirm", "Confirm"},
                {"Close", "Close"},
                {"TryAgain", "Try Again"},
                {"Notification", "Notice"},
                {"ErrorLoadInfo", "Cannot load information"},
                {"ErrorPlay", "Playback Error"},
            },

            // ===================== JAPANESE =====================
            ["ja"] = new()
            {
                {"TabHome", "ホーム"},
                {"TabExplore", "探索"},
                {"TabScanQR", "QRスキャン"},
                {"TabTour", "ツアー"},
                {"TabSettings", "設定"},
                {"HomeTitle", "ビンカン食道街"},
                {"SubTitle", "第4区で有名なカタツムリとシーフードのパラダイス。夜は活気に溢れています。"},
                {"Listen", "音声再生"},
                {"Stop", "停止"},
                {"Map", "地図を見る"},
                {"SelectLang", "言語を選択"},
                {"Cancel", "キャンセル"},
                {"NoNarration", "このレストランには現在ナレーションがありません。"},
                {"NoNarrationLang", "選択した言語のナレーションはまだありません。"},
                {"RestaurantDetail", "レストラン詳細"},
                {"PlayNarration", "▶ ナレーション再生"},
                {"StopNarration", "⏹ ナレーション停止"},
                {"MapDirection", "道案内マップ"},
                {"OpenGoogleMaps", "🧭 Google Mapsで案内"},
                {"DishList", "メニュー"},
                {"PriceFormat", "価格: {0} VND"},
                {"NoLocation", "📍 レストランはまだ地図上の位置を更新していません。"},
                {"YouAreHere", "現在地"},
                {"DistanceFormat", "📍 現在地から{0} km"},
                {"NoCoordinate", "📍 レストランの座標が未更新"},
                {"LoadingAudio", "⏳ 読み込み中..."},
                {"DownloadingAudio", "音声をダウンロード中..."},
                {"PlayingAudio", "ナレーション再生中..."},
                {"PlayingOffline", "ナレーション再生中（オフライン）..."},
                {"ReadingAloud", "読み上げ中..."},
                {"AudioError", "音声再生エラー"},
                {"TourList", "観光ツアー"},
                {"ChooseJourney", "グルメ探索ルートを選択"},
                {"NoTours", "ツアーはまだありません"},
                {"Destinations", "スポット"},
                {"Free", "無料"},
                {"TourJourney", "ツアー行程"},
                {"Previous", "⬅ 前へ"},
                {"Next", "次へ ➡"},
                {"PlayAudio", "🔊 聴く"},
                {"StopAudio", "⏹ 停止"},
                {"Navigate", "🧭 ナビ"},
                {"PointOf", "▶ {0}/{1}地点"},
                {"TotalPoints", "合計: {0}地点"},
                {"PointLabel", "地点 {0}"},
                {"BuyTour", "💳 ツアー購入"},
                {"BuyTourPrice", "💳 {0}₫で購入"},
                {"NeedPayment", "🔒 ナレーションを聴くには支払いが必要です"},
                {"NeedPaymentPrice", "🔒 ナレーションを聴くには{0}₫のお支払い"},
                {"NeedPaymentMsg", "このツアーは{0}₫です。ナレーションを聴くにはお支払いが必要です。"},
                {"NoNarrationPOI", "{0}のナレーションはまだありません"},
                {"TourNotFound", "ツアーが見つからないか、目的地がありません"},
                {"TourLoadError", "ツアーを読み込めません: {0}"},
                {"PriceTag", "💰 {0}₫"},
                {"FreeTag", "✅ 無料"},
                {"Settings", "⚙️ 設定"},
                {"SettingsTitle", "設定"},
                {"Profile", "プロフィール"},
                {"ViewEditProfile", "個人情報の表示と編集"},
                {"AnonymousMode", "🕶️ 匿名モード"},
                {"AnonymousModeLabel", "匿名モード"},
                {"AnonymousDesc", "有効にすると、移動データは個人情報に紐付けられません。"},
                {"AnonymousOn", "🟢 ON — 匿名モード中 ({0})"},
                {"AnonymousOff", "🔴 OFF — データはアカウントに紐付け"},
                {"GpsSettings", "📡 GPS設定"},
                {"DetectionRadius", "📡 検出半径"},
                {"DetectionRadiusDesc", "地点に近づいた時にナレーションを自動再生する最大距離。"},
                {"MovementDistance", "🚶 移動距離"},
                {"MovementDistanceDesc", "次のナレーションを起動するために最低限歩く距離。"},
                {"ResetDefault", "🔄 デフォルトに戻す"},
                {"ServerConnection", "🌐 サーバー接続"},
                {"ServerIP", "サーバーIPアドレス"},
                {"ServerIPDesc", "WiFi経由で接続する実機用。"},
                {"OfflineData", "📥 オフラインデータ"},
                {"DownloadOfflineDesc", "オフライン使用のためにデータをダウンロード"},
                {"SyncOffline", "📥 オフラインデータを同期"},
                {"SyncingRestaurants", "⏳ レストランを同期中..."},
                {"SyncingTours", "⏳ ツアーを同期中..."},
                {"DownloadingAudioFiles", "⏳ 音声ファイルをダウンロード中..."},
                {"SyncSuccess", "✅ 同期成功！"},
                {"SyncError", "❌ エラー: {0}"},
                {"NeedNetwork", "オフライン同期にはネットワーク接続が必要です。"},
                {"NeverSynced", "未同期"},
                {"LastSyncPrefix", "最終同期: {0}"},
                {"ProfileTitle", "プロフィール"},
                {"Email", "メール"},
                {"Phone", "電話番号"},
                {"Address", "住所"},
                {"EditProfile", "✏️ プロフィール編集"},
                {"Logout", "🚪 ログアウト"},
                {"LogoutConfirm", "確認"},
                {"LogoutConfirmMsg", "ログアウトしますか？"},
                {"LogoutBtn", "ログアウト"},
                {"NotUpdated", "未更新"},
                {"Welcome", "フードストリートへようこそ！"},
                {"EmailPlaceholder", "メールアドレス"},
                {"PasswordPlaceholder", "パスワード"},
                {"LoginBtn", "ログイン"},
                {"NoAccount", "アカウントがありませんか？"},
                {"RegisterNow", "今すぐ登録"},
                {"ServerSettings", "⚙ サーバーIP設定"},
                {"Authenticating", "認証中..."},
                {"LoginError", "メールまたはパスワードが間違っています"},
                {"LoginInputError", "メールとパスワードを入力してください"},
                {"ConnectionError", "サーバーに接続できません"},
                {"ServerSettingsTitle", "サーバー設定"},
                {"ServerSettingsMsg", "パソコンのWiFi IPアドレスを入力してください:"},
                {"ServerSaved", "保存しました"},
                {"ServerSavedMsg", "サーバーIP: {0}\nアプリを再起動してください。"},
                {"RegisterTitle", "新規登録"},
                {"FullNamePlaceholder", "氏名"},
                {"ChooseAccountType", "アカウントタイプを選択"},
                {"RegisterBtn", "登録"},
                {"BackToLogin", "ログインに戻る"},
                {"RegisterInputError", "すべての項目を入力してください"},
                {"RegisterFailed", "登録に失敗しました"},
                {"RegisterSuccess", "登録成功"},
                {"Success", "成功"},
                {"NoServerConnection", "サーバーに接続できません"},
                {"Error", "エラー"},
                {"OK", "OK"},
                {"Confirm", "確認"},
                {"Close", "閉じる"},
                {"TryAgain", "再試行"},
                {"Notification", "通知"},
                {"ErrorLoadInfo", "情報を読み込めません"},
                {"ErrorPlay", "再生エラー"},
            },

            // ===================== FRENCH =====================
            ["fr"] = new()
            {
                {"TabHome", "Accueil"},
                {"TabExplore", "Explorer"},
                {"TabScanQR", "Scanner QR"},
                {"TabTour", "Tour"},
                {"TabSettings", "Paramètres"},
                {"HomeTitle", "Rue culinaire de Vinh Khanh"},
                {"SubTitle", "Célèbre paradis des escargots et fruits de mer au District 4, animé la nuit."},
                {"Listen", "Écouter"},
                {"Stop", "Arrêter"},
                {"Map", "Voir la carte"},
                {"SelectLang", "Choisir la langue"},
                {"Cancel", "Annuler"},
                {"NoNarration", "Ce restaurant n'a pas encore de narration."},
                {"NoNarrationLang", "Aucune narration disponible dans la langue sélectionnée."},
                {"RestaurantDetail", "Détails du restaurant"},
                {"PlayNarration", "▶ Lire la narration"},
                {"StopNarration", "⏹ Arrêter la narration"},
                {"MapDirection", "Carte d'itinéraire"},
                {"OpenGoogleMaps", "🧭 Ouvrir Google Maps"},
                {"DishList", "Menu des plats"},
                {"PriceFormat", "Prix: {0} VND"},
                {"NoLocation", "📍 Le restaurant n'a pas encore mis à jour sa position."},
                {"YouAreHere", "Vous êtes ici"},
                {"DistanceFormat", "📍 {0} km de votre position"},
                {"NoCoordinate", "📍 Coordonnées non mises à jour"},
                {"LoadingAudio", "⏳ Chargement..."},
                {"DownloadingAudio", "Téléchargement audio..."},
                {"PlayingAudio", "Lecture de la narration..."},
                {"PlayingOffline", "Lecture de la narration (hors ligne)..."},
                {"ReadingAloud", "Lecture en cours..."},
                {"AudioError", "Erreur de lecture audio"},
                {"TourList", "Tours touristiques"},
                {"ChooseJourney", "Choisissez un parcours culinaire"},
                {"NoTours", "Aucun tour disponible"},
                {"Destinations", "destinations"},
                {"Free", "Gratuit"},
                {"TourJourney", "Parcours du tour"},
                {"Previous", "⬅ Précédent"},
                {"Next", "Suivant ➡"},
                {"PlayAudio", "🔊 Écouter"},
                {"StopAudio", "⏹ Arrêter"},
                {"Navigate", "🧭 Naviguer"},
                {"PointOf", "▶ Point {0}/{1}"},
                {"TotalPoints", "Total: {0} points"},
                {"PointLabel", "POINT {0}"},
                {"BuyTour", "💳 Acheter le tour"},
                {"BuyTourPrice", "💳 Acheter {0}₫"},
                {"NeedPayment", "🔒 Paiement requis pour écouter la narration"},
                {"NeedPaymentPrice", "🔒 Payez {0}₫ pour écouter la narration"},
                {"NeedPaymentMsg", "Ce tour coûte {0}₫. Vous devez payer pour écouter la narration."},
                {"NoNarrationPOI", "Pas de narration pour {0}"},
                {"TourNotFound", "Tour introuvable ou sans destinations"},
                {"TourLoadError", "Impossible de charger le tour: {0}"},
                {"PriceTag", "💰 {0}₫"},
                {"FreeTag", "✅ Gratuit"},
                {"Settings", "⚙️ Paramètres"},
                {"SettingsTitle", "Paramètres"},
                {"Profile", "Mon profil"},
                {"ViewEditProfile", "Voir et modifier les informations personnelles"},
                {"AnonymousMode", "🕶️ Mode anonyme"},
                {"AnonymousModeLabel", "Mode anonyme"},
                {"AnonymousDesc", "Activé, vos données de déplacement ne sont pas liées à votre identité."},
                {"AnonymousOn", "🟢 ON — Vous êtes anonyme ({0})"},
                {"AnonymousOff", "🔴 OFF — Données liées à votre compte"},
                {"GpsSettings", "📡 Paramètres GPS"},
                {"DetectionRadius", "📡 Rayon de détection"},
                {"DetectionRadiusDesc", "Distance maximale pour lire automatiquement la narration."},
                {"MovementDistance", "🚶 Distance de déplacement"},
                {"MovementDistanceDesc", "Distance minimale à parcourir pour déclencher la narration suivante."},
                {"ResetDefault", "🔄 Réinitialiser"},
                {"ServerConnection", "🌐 Connexion serveur"},
                {"ServerIP", "Adresse IP du serveur"},
                {"ServerIPDesc", "Pour les appareils réels via WiFi."},
                {"OfflineData", "📥 Données hors ligne"},
                {"DownloadOfflineDesc", "Télécharger les données pour une utilisation hors ligne"},
                {"SyncOffline", "📥 Synchroniser les données"},
                {"SyncingRestaurants", "⏳ Synchronisation des restaurants..."},
                {"SyncingTours", "⏳ Synchronisation des tours..."},
                {"DownloadingAudioFiles", "⏳ Téléchargement des fichiers audio..."},
                {"SyncSuccess", "✅ Synchronisation réussie!"},
                {"SyncError", "❌ Erreur: {0}"},
                {"NeedNetwork", "Connexion réseau requise pour la synchronisation."},
                {"NeverSynced", "Jamais synchronisé"},
                {"LastSyncPrefix", "Dernière sync: {0}"},
                {"ProfileTitle", "Mon profil"},
                {"Email", "Email"},
                {"Phone", "Téléphone"},
                {"Address", "Adresse"},
                {"EditProfile", "✏️ Modifier le profil"},
                {"Logout", "🚪 Déconnexion"},
                {"LogoutConfirm", "Confirmer"},
                {"LogoutConfirmMsg", "Êtes-vous sûr de vouloir vous déconnecter?"},
                {"LogoutBtn", "Déconnexion"},
                {"NotUpdated", "Non mis à jour"},
                {"Welcome", "Bienvenue à la Rue culinaire!"},
                {"EmailPlaceholder", "Votre email"},
                {"PasswordPlaceholder", "Mot de passe"},
                {"LoginBtn", "Se connecter"},
                {"NoAccount", "Pas de compte?"},
                {"RegisterNow", "S'inscrire"},
                {"ServerSettings", "⚙ Paramètres IP du serveur"},
                {"Authenticating", "Authentification..."},
                {"LoginError", "Email ou mot de passe incorrect"},
                {"LoginInputError", "Veuillez entrer email et mot de passe"},
                {"ConnectionError", "Impossible de se connecter au serveur"},
                {"ServerSettingsTitle", "Paramètres du serveur"},
                {"ServerSettingsMsg", "Entrez l'adresse IP WiFi de votre ordinateur:"},
                {"ServerSaved", "Enregistré"},
                {"ServerSavedMsg", "IP du serveur: {0}\nVeuillez redémarrer l'application."},
                {"RegisterTitle", "INSCRIPTION"},
                {"FullNamePlaceholder", "Nom complet"},
                {"ChooseAccountType", "Type de compte"},
                {"RegisterBtn", "S'inscrire"},
                {"BackToLogin", "Retour à la connexion"},
                {"RegisterInputError", "Veuillez remplir tous les champs"},
                {"RegisterFailed", "Échec de l'inscription"},
                {"RegisterSuccess", "Inscription réussie"},
                {"Success", "Succès"},
                {"NoServerConnection", "Impossible de se connecter au serveur"},
                {"Error", "Erreur"},
                {"OK", "OK"},
                {"Confirm", "Confirmer"},
                {"Close", "Fermer"},
                {"TryAgain", "Réessayer"},
                {"Notification", "Notification"},
                {"ErrorLoadInfo", "Impossible de charger les informations"},
                {"ErrorPlay", "Erreur de lecture"},
            },

            // ===================== KOREAN =====================
            ["ko"] = new()
            {
                {"TabHome", "홈"},
                {"TabExplore", "탐색"},
                {"TabScanQR", "QR 스캔"},
                {"TabTour", "투어"},
                {"TabSettings", "설정"},
                {"HomeTitle", "빈칸 음식 거리"},
                {"SubTitle", "4구의 유명한 달팽이와 해산물 낙원. 밤에 활기찹니다."},
                {"Listen", "오디오 듣기"},
                {"Stop", "중지"},
                {"Map", "지도 보기"},
                {"SelectLang", "언어 선택"},
                {"Cancel", "취소"},
                {"NoNarration", "이 레스토랑은 현재 설명이 없습니다."},
                {"NoNarrationLang", "선택한 언어의 해설이 아직 없습니다."},
                {"RestaurantDetail", "레스토랑 상세"},
                {"PlayNarration", "▶ 해설 재생"},
                {"StopNarration", "⏹ 해설 중지"},
                {"MapDirection", "길찾기 지도"},
                {"OpenGoogleMaps", "🧭 Google Maps 열기"},
                {"DishList", "메뉴"},
                {"PriceFormat", "가격: {0} VND"},
                {"NoLocation", "📍 레스토랑이 아직 지도에 위치를 업데이트하지 않았습니다."},
                {"YouAreHere", "현재 위치"},
                {"DistanceFormat", "📍 현재 위치에서 {0} km"},
                {"NoCoordinate", "📍 좌표 미업데이트"},
                {"LoadingAudio", "⏳ 로딩 중..."},
                {"DownloadingAudio", "오디오 다운로드 중..."},
                {"PlayingAudio", "해설 재생 중..."},
                {"PlayingOffline", "해설 재생 중 (오프라인)..."},
                {"ReadingAloud", "읽는 중..."},
                {"AudioError", "오디오 재생 오류"},
                {"TourList", "관광 투어"},
                {"ChooseJourney", "음식 탐방 여정을 선택하세요"},
                {"NoTours", "투어가 없습니다"},
                {"Destinations", "목적지"},
                {"Free", "무료"},
                {"TourJourney", "투어 여정"},
                {"Previous", "⬅ 이전"},
                {"Next", "다음 ➡"},
                {"PlayAudio", "🔊 듣기"},
                {"StopAudio", "⏹ 중지"},
                {"Navigate", "🧭 길안내"},
                {"PointOf", "▶ {0}/{1}번째"},
                {"TotalPoints", "총: {0}곳"},
                {"PointLabel", "{0}번째"},
                {"BuyTour", "💳 투어 구매"},
                {"BuyTourPrice", "💳 {0}₫ 구매"},
                {"NeedPayment", "🔒 해설을 듣기 위해 결제가 필요합니다"},
                {"NeedPaymentPrice", "🔒 해설을 듣기 위해 {0}₫ 결제"},
                {"NeedPaymentMsg", "이 투어는 {0}₫입니다. 해설을 듣기 위해 결제가 필요합니다."},
                {"NoNarrationPOI", "{0}에 대한 해설이 없습니다"},
                {"TourNotFound", "투어를 찾을 수 없거나 목적지가 없습니다"},
                {"TourLoadError", "투어를 불러올 수 없습니다: {0}"},
                {"PriceTag", "💰 {0}₫"},
                {"FreeTag", "✅ 무료"},
                {"Settings", "⚙️ 설정"},
                {"SettingsTitle", "설정"},
                {"Profile", "내 프로필"},
                {"ViewEditProfile", "개인 정보 보기 및 편집"},
                {"AnonymousMode", "🕶️ 익명 모드"},
                {"AnonymousModeLabel", "익명 모드"},
                {"AnonymousDesc", "활성화하면 이동 데이터가 개인 정보와 연결되지 않습니다."},
                {"AnonymousOn", "🟢 ON — 익명 모드 중 ({0})"},
                {"AnonymousOff", "🔴 OFF — 데이터가 계정에 연결됨"},
                {"GpsSettings", "📡 GPS 설정"},
                {"DetectionRadius", "📡 감지 반경"},
                {"DetectionRadiusDesc", "장소에 가까워졌을 때 자동 재생할 최대 거리."},
                {"MovementDistance", "🚶 이동 거리"},
                {"MovementDistanceDesc", "다음 해설을 작동시키기 위해 최소 걸어야 할 거리."},
                {"ResetDefault", "🔄 기본값으로 재설정"},
                {"ServerConnection", "🌐 서버 연결"},
                {"ServerIP", "서버 IP 주소"},
                {"ServerIPDesc", "WiFi를 통해 연결하는 실제 기기용."},
                {"OfflineData", "📥 오프라인 데이터"},
                {"DownloadOfflineDesc", "오프라인 사용을 위해 데이터 다운로드"},
                {"SyncOffline", "📥 오프라인 데이터 동기화"},
                {"SyncingRestaurants", "⏳ 레스토랑 동기화 중..."},
                {"SyncingTours", "⏳ 투어 동기화 중..."},
                {"DownloadingAudioFiles", "⏳ 오디오 파일 다운로드 중..."},
                {"SyncSuccess", "✅ 동기화 성공!"},
                {"SyncError", "❌ 오류: {0}"},
                {"NeedNetwork", "오프라인 동기화에는 네트워크 연결이 필요합니다."},
                {"NeverSynced", "동기화한 적 없음"},
                {"LastSyncPrefix", "마지막 동기화: {0}"},
                {"ProfileTitle", "내 프로필"},
                {"Email", "이메일"},
                {"Phone", "전화번호"},
                {"Address", "주소"},
                {"EditProfile", "✏️ 프로필 편집"},
                {"Logout", "🚪 로그아웃"},
                {"LogoutConfirm", "확인"},
                {"LogoutConfirmMsg", "로그아웃 하시겠습니까?"},
                {"LogoutBtn", "로그아웃"},
                {"NotUpdated", "미업데이트"},
                {"Welcome", "푸드 스트리트에 오신 것을 환영합니다!"},
                {"EmailPlaceholder", "이메일"},
                {"PasswordPlaceholder", "비밀번호"},
                {"LoginBtn", "로그인"},
                {"NoAccount", "계정이 없으신가요?"},
                {"RegisterNow", "지금 가입"},
                {"ServerSettings", "⚙ 서버 IP 설정"},
                {"Authenticating", "인증 중..."},
                {"LoginError", "이메일 또는 비밀번호가 잘못되었습니다"},
                {"LoginInputError", "이메일과 비밀번호를 입력하세요"},
                {"ConnectionError", "서버에 연결할 수 없습니다"},
                {"ServerSettingsTitle", "서버 설정"},
                {"ServerSettingsMsg", "컴퓨터의 WiFi IP 주소를 입력하세요:"},
                {"ServerSaved", "저장됨"},
                {"ServerSavedMsg", "서버 IP: {0}\n앱을 다시 시작하세요."},
                {"RegisterTitle", "회원가입"},
                {"FullNamePlaceholder", "이름"},
                {"ChooseAccountType", "계정 유형 선택"},
                {"RegisterBtn", "가입"},
                {"BackToLogin", "로그인으로 돌아가기"},
                {"RegisterInputError", "모든 정보를 입력하세요"},
                {"RegisterFailed", "가입 실패"},
                {"RegisterSuccess", "가입 성공"},
                {"Success", "성공"},
                {"NoServerConnection", "서버에 연결할 수 없습니다"},
                {"Error", "오류"},
                {"OK", "확인"},
                {"Confirm", "확인"},
                {"Close", "닫기"},
                {"TryAgain", "재시도"},
                {"Notification", "알림"},
                {"ErrorLoadInfo", "정보를 불러올 수 없습니다"},
                {"ErrorPlay", "재생 오류"},
            },

            // ===================== CHINESE =====================
            ["zh"] = new()
            {
                {"TabHome", "首页"},
                {"TabExplore", "发现"},
                {"TabScanQR", "扫码"},
                {"TabTour", "旅游"},
                {"TabSettings", "设置"},
                {"HomeTitle", "永庆美食街"},
                {"SubTitle", "第四区著名的螺类和海鲜天堂，夜晚热闹非凡。"},
                {"Listen", "播放音频"},
                {"Stop", "停止"},
                {"Map", "查看地图"},
                {"SelectLang", "选择语言"},
                {"Cancel", "取消"},
                {"NoNarration", "该餐厅目前没有解说。"},
                {"NoNarrationLang", "所选语言暂无解说。"},
                {"RestaurantDetail", "餐厅详情"},
                {"PlayNarration", "▶ 播放解说"},
                {"StopNarration", "⏹ 停止解说"},
                {"MapDirection", "导航地图"},
                {"OpenGoogleMaps", "🧭 打开Google地图导航"},
                {"DishList", "菜单"},
                {"PriceFormat", "价格: {0} 越盾"},
                {"NoLocation", "📍 餐厅尚未在地图上更新位置。"},
                {"YouAreHere", "您在这里"},
                {"DistanceFormat", "📍 距您{0}公里"},
                {"NoCoordinate", "📍 餐厅坐标未更新"},
                {"LoadingAudio", "⏳ 加载中..."},
                {"DownloadingAudio", "下载音频中..."},
                {"PlayingAudio", "正在播放解说..."},
                {"PlayingOffline", "正在播放解说（离线）..."},
                {"ReadingAloud", "朗读中..."},
                {"AudioError", "音频播放错误"},
                {"TourList", "旅游线路"},
                {"ChooseJourney", "选择美食探索之旅"},
                {"NoTours", "暂无旅游线路"},
                {"Destinations", "个目的地"},
                {"Free", "免费"},
                {"TourJourney", "旅游行程"},
                {"Previous", "⬅ 上一个"},
                {"Next", "下一个 ➡"},
                {"PlayAudio", "🔊 收听"},
                {"StopAudio", "⏹ 停止"},
                {"Navigate", "🧭 导航"},
                {"PointOf", "▶ 第{0}/{1}站"},
                {"TotalPoints", "共: {0}站"},
                {"PointLabel", "第{0}站"},
                {"BuyTour", "💳 购买旅游"},
                {"BuyTourPrice", "💳 购买 {0}₫"},
                {"NeedPayment", "🔒 需要付款才能收听解说"},
                {"NeedPaymentPrice", "🔒 支付{0}₫收听解说"},
                {"NeedPaymentMsg", "此旅游费用为{0}₫。需要付款才能收听解说。"},
                {"NoNarrationPOI", "{0}暂无解说"},
                {"TourNotFound", "未找到旅游线路或无目的地"},
                {"TourLoadError", "无法加载旅游: {0}"},
                {"PriceTag", "💰 {0}₫"},
                {"FreeTag", "✅ 免费"},
                {"Settings", "⚙️ 设置"},
                {"SettingsTitle", "设置"},
                {"Profile", "个人资料"},
                {"ViewEditProfile", "查看和编辑个人信息"},
                {"AnonymousMode", "🕶️ 匿名模式"},
                {"AnonymousModeLabel", "匿名模式"},
                {"AnonymousDesc", "开启后，您的移动数据不会与您的身份关联。"},
                {"AnonymousOn", "🟢 开启 — 匿名模式中 ({0})"},
                {"AnonymousOff", "🔴 关闭 — 数据与您的账户关联"},
                {"GpsSettings", "📡 GPS设置"},
                {"DetectionRadius", "📡 检测半径"},
                {"DetectionRadiusDesc", "接近地点时自动播放解说的最大距离。"},
                {"MovementDistance", "🚶 移动距离"},
                {"MovementDistanceDesc", "触发下一段解说需要行走的最小距离。"},
                {"ResetDefault", "🔄 恢复默认"},
                {"ServerConnection", "🌐 服务器连接"},
                {"ServerIP", "服务器IP地址"},
                {"ServerIPDesc", "通过WiFi连接的实体设备使用。"},
                {"OfflineData", "📥 离线数据"},
                {"DownloadOfflineDesc", "下载数据以便离线使用"},
                {"SyncOffline", "📥 同步离线数据"},
                {"SyncingRestaurants", "⏳ 正在同步餐厅..."},
                {"SyncingTours", "⏳ 正在同步旅游..."},
                {"DownloadingAudioFiles", "⏳ 正在下载音频文件..."},
                {"SyncSuccess", "✅ 同步成功！"},
                {"SyncError", "❌ 错误: {0}"},
                {"NeedNetwork", "离线同步需要网络连接。"},
                {"NeverSynced", "从未同步"},
                {"LastSyncPrefix", "上次同步: {0}"},
                {"ProfileTitle", "个人资料"},
                {"Email", "邮箱"},
                {"Phone", "电话"},
                {"Address", "地址"},
                {"EditProfile", "✏️ 编辑资料"},
                {"Logout", "🚪 退出登录"},
                {"LogoutConfirm", "确认"},
                {"LogoutConfirmMsg", "确定要退出登录吗？"},
                {"LogoutBtn", "退出"},
                {"NotUpdated", "未更新"},
                {"Welcome", "欢迎回到美食街！"},
                {"EmailPlaceholder", "您的邮箱"},
                {"PasswordPlaceholder", "密码"},
                {"LoginBtn", "登录"},
                {"NoAccount", "没有账户？"},
                {"RegisterNow", "立即注册"},
                {"ServerSettings", "⚙ 服务器IP设置"},
                {"Authenticating", "正在验证..."},
                {"LoginError", "邮箱或密码错误"},
                {"LoginInputError", "请输入邮箱和密码"},
                {"ConnectionError", "无法连接到服务器"},
                {"ServerSettingsTitle", "服务器设置"},
                {"ServerSettingsMsg", "输入电脑的WiFi IP地址:"},
                {"ServerSaved", "已保存"},
                {"ServerSavedMsg", "服务器IP: {0}\n请重启应用以生效。"},
                {"RegisterTitle", "注册"},
                {"FullNamePlaceholder", "姓名"},
                {"ChooseAccountType", "选择账户类型"},
                {"RegisterBtn", "注册"},
                {"BackToLogin", "返回登录"},
                {"RegisterInputError", "请填写所有信息"},
                {"RegisterFailed", "注册失败"},
                {"RegisterSuccess", "注册成功"},
                {"Success", "成功"},
                {"NoServerConnection", "无法连接到服务器"},
                {"Error", "错误"},
                {"OK", "确定"},
                {"Confirm", "确认"},
                {"Close", "关闭"},
                {"TryAgain", "重试"},
                {"Notification", "通知"},
                {"ErrorLoadInfo", "无法加载信息"},
                {"ErrorPlay", "播放错误"},
            },

            // ===================== THAI =====================
            ["th"] = new()
            {
                {"TabHome", "หน้าแรก"},
                {"TabExplore", "สำรวจ"},
                {"TabScanQR", "สแกน QR"},
                {"TabTour", "ทัวร์"},
                {"TabSettings", "ตั้งค่า"},
                {"HomeTitle", "ถนนอาหารวินห์คานห์"},
                {"SubTitle", "สวรรค์ของหอยทากและอาหารทะเลชื่อดังในเขต 4 คึกคักยามค่ำคืน"},
                {"Listen", "ฟังเสียงบรรยาย"},
                {"Stop", "หยุด"},
                {"Map", "ดูแผนที่"},
                {"SelectLang", "เลือกภาษา"},
                {"Cancel", "ยกเลิก"},
                {"NoNarration", "ร้านอาหารนี้ยังไม่มีเสียงบรรยาย"},
                {"NoNarrationLang", "ยังไม่มีเสียงบรรยายในภาษาที่เลือก"},
                {"RestaurantDetail", "รายละเอียดร้านอาหาร"},
                {"PlayNarration", "▶ เล่นเสียงบรรยาย"},
                {"StopNarration", "⏹ หยุดเสียงบรรยาย"},
                {"MapDirection", "แผนที่นำทาง"},
                {"OpenGoogleMaps", "🧭 เปิด Google Maps นำทาง"},
                {"DishList", "รายการอาหาร"},
                {"PriceFormat", "ราคา: {0} ดอง"},
                {"NoLocation", "📍 ร้านอาหารยังไม่ได้อัปเดตตำแหน่งบนแผนที่"},
                {"YouAreHere", "คุณอยู่ที่นี่"},
                {"DistanceFormat", "📍 {0} กม. จากตำแหน่งของคุณ"},
                {"NoCoordinate", "📍 ร้านอาหารยังไม่ได้อัปเดตพิกัด"},
                {"LoadingAudio", "⏳ กำลังโหลด..."},
                {"DownloadingAudio", "กำลังดาวน์โหลดเสียง..."},
                {"PlayingAudio", "กำลังเล่นเสียงบรรยาย..."},
                {"PlayingOffline", "กำลังเล่นเสียงบรรยาย (ออฟไลน์)..."},
                {"ReadingAloud", "กำลังอ่าน..."},
                {"AudioError", "เกิดข้อผิดพลาดในการเล่นเสียง"},
                {"TourList", "ทัวร์ท่องเที่ยว"},
                {"ChooseJourney", "เลือกเส้นทางสำรวจอาหาร"},
                {"NoTours", "ยังไม่มีทัวร์"},
                {"Destinations", "จุดหมาย"},
                {"Free", "ฟรี"},
                {"TourJourney", "เส้นทางทัวร์"},
                {"Previous", "⬅ ก่อนหน้า"},
                {"Next", "ถัดไป ➡"},
                {"PlayAudio", "🔊 ฟัง"},
                {"StopAudio", "⏹ หยุด"},
                {"Navigate", "🧭 นำทาง"},
                {"PointOf", "▶ จุดที่ {0}/{1}"},
                {"TotalPoints", "ทั้งหมด: {0} จุด"},
                {"PointLabel", "จุดที่ {0}"},
                {"BuyTour", "💳 ซื้อทัวร์"},
                {"BuyTourPrice", "💳 ซื้อ {0}₫"},
                {"NeedPayment", "🔒 ต้องชำระเงินเพื่อฟังเสียงบรรยาย"},
                {"NeedPaymentPrice", "🔒 ชำระ {0}₫ เพื่อฟังเสียงบรรยาย"},
                {"NeedPaymentMsg", "ทัวร์นี้ราคา {0}₫ คุณต้องชำระเงินเพื่อฟังเสียงบรรยาย"},
                {"NoNarrationPOI", "ยังไม่มีเสียงบรรยายสำหรับ {0}"},
                {"TourNotFound", "ไม่พบทัวร์หรือทัวร์ยังไม่มีจุดหมาย"},
                {"TourLoadError", "ไม่สามารถโหลดทัวร์: {0}"},
                {"PriceTag", "💰 {0}₫"},
                {"FreeTag", "✅ ฟรี"},
                {"Settings", "⚙️ ตั้งค่า"},
                {"SettingsTitle", "ตั้งค่า"},
                {"Profile", "โปรไฟล์ของฉัน"},
                {"ViewEditProfile", "ดูและแก้ไขข้อมูลส่วนตัว"},
                {"AnonymousMode", "🕶️ โหมดไม่ระบุตัวตน"},
                {"AnonymousModeLabel", "โหมดไม่ระบุตัวตน"},
                {"AnonymousDesc", "เมื่อเปิด ข้อมูลการเดินทางจะไม่เชื่อมโยงกับตัวตนของคุณ"},
                {"AnonymousOn", "🟢 เปิด — คุณกำลังใช้งานแบบไม่ระบุตัวตน ({0})"},
                {"AnonymousOff", "🔴 ปิด — ข้อมูลเชื่อมโยงกับบัญชีของคุณ"},
                {"GpsSettings", "📡 ตั้งค่า GPS"},
                {"DetectionRadius", "📡 รัศมีการตรวจจับ"},
                {"DetectionRadiusDesc", "ระยะทางสูงสุดที่จะเล่นเสียงบรรยายอัตโนมัติเมื่อเข้าใกล้สถานที่"},
                {"MovementDistance", "🚶 ระยะทางการเดิน"},
                {"MovementDistanceDesc", "ระยะทางขั้นต่ำที่ต้องเดินเพื่อเปิดเสียงบรรยายถัดไป"},
                {"ResetDefault", "🔄 รีเซ็ตค่าเริ่มต้น"},
                {"ServerConnection", "🌐 เชื่อมต่อเซิร์ฟเวอร์"},
                {"ServerIP", "ที่อยู่ IP เซิร์ฟเวอร์"},
                {"ServerIPDesc", "สำหรับอุปกรณ์จริงที่เชื่อมต่อผ่าน WiFi"},
                {"OfflineData", "📥 ข้อมูลออฟไลน์"},
                {"DownloadOfflineDesc", "ดาวน์โหลดข้อมูลเพื่อใช้เมื่อไม่มีเครือข่าย"},
                {"SyncOffline", "📥 ซิงค์ข้อมูลออฟไลน์"},
                {"SyncingRestaurants", "⏳ กำลังซิงค์ร้านอาหาร..."},
                {"SyncingTours", "⏳ กำลังซิงค์ทัวร์..."},
                {"DownloadingAudioFiles", "⏳ กำลังดาวน์โหลดไฟล์เสียง..."},
                {"SyncSuccess", "✅ ซิงค์สำเร็จ!"},
                {"SyncError", "❌ ข้อผิดพลาด: {0}"},
                {"NeedNetwork", "ต้องเชื่อมต่อเครือข่ายเพื่อซิงค์ข้อมูลออฟไลน์"},
                {"NeverSynced", "ยังไม่เคยซิงค์"},
                {"LastSyncPrefix", "ครั้งล่าสุด: {0}"},
                {"ProfileTitle", "โปรไฟล์ของฉัน"},
                {"Email", "อีเมล"},
                {"Phone", "เบอร์โทรศัพท์"},
                {"Address", "ที่อยู่"},
                {"EditProfile", "✏️ แก้ไขโปรไฟล์"},
                {"Logout", "🚪 ออกจากระบบ"},
                {"LogoutConfirm", "ยืนยัน"},
                {"LogoutConfirmMsg", "คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?"},
                {"LogoutBtn", "ออกจากระบบ"},
                {"NotUpdated", "ยังไม่อัปเดต"},
                {"Welcome", "ยินดีต้อนรับกลับสู่ถนนอาหาร!"},
                {"EmailPlaceholder", "อีเมลของคุณ"},
                {"PasswordPlaceholder", "รหัสผ่าน"},
                {"LoginBtn", "เข้าสู่ระบบ"},
                {"NoAccount", "ยังไม่มีบัญชี?"},
                {"RegisterNow", "สมัครเลย"},
                {"ServerSettings", "⚙ ตั้งค่า IP เซิร์ฟเวอร์"},
                {"Authenticating", "กำลังยืนยันตัวตน..."},
                {"LoginError", "อีเมลหรือรหัสผ่านไม่ถูกต้อง"},
                {"LoginInputError", "กรุณากรอกอีเมลและรหัสผ่าน"},
                {"ConnectionError", "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์"},
                {"ServerSettingsTitle", "ตั้งค่าเซิร์ฟเวอร์"},
                {"ServerSettingsMsg", "กรอกที่อยู่ IP WiFi ของคอมพิวเตอร์:"},
                {"ServerSaved", "บันทึกแล้ว"},
                {"ServerSavedMsg", "IP เซิร์ฟเวอร์: {0}\nกรุณาเปิดแอปใหม่เพื่อใช้งาน"},
                {"RegisterTitle", "สมัครสมาชิก"},
                {"FullNamePlaceholder", "ชื่อ-นามสกุล"},
                {"ChooseAccountType", "เลือกประเภทบัญชี"},
                {"RegisterBtn", "สมัคร"},
                {"BackToLogin", "กลับไปเข้าสู่ระบบ"},
                {"RegisterInputError", "กรุณากรอกข้อมูลให้ครบถ้วน"},
                {"RegisterFailed", "สมัครสมาชิกไม่สำเร็จ"},
                {"RegisterSuccess", "สมัครสมาชิกสำเร็จ"},
                {"Success", "สำเร็จ"},
                {"NoServerConnection", "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์"},
                {"Error", "ข้อผิดพลาด"},
                {"OK", "ตกลง"},
                {"Confirm", "ยืนยัน"},
                {"Close", "ปิด"},
                {"TryAgain", "ลองอีกครั้ง"},
                {"Notification", "การแจ้งเตือน"},
                {"ErrorLoadInfo", "ไม่สามารถโหลดข้อมูล"},
                {"ErrorPlay", "เกิดข้อผิดพลาดในการเล่น"},
            },
        };

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
